# Generated by Django 5.0 on 2023-12-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_icon',
        ),
    ]
