# Generated by Django 5.0 on 2023-12-31 10:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service2', '0002_remove_service_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug_name',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='service_title', unique=True),
        ),
    ]
