# Generated by Django 5.0 on 2023-12-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service2', '0004_savedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedata',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='savedata',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
