# Generated by Django 5.0 on 2024-01-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service2', '0005_alter_savedata_address_alter_savedata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_field',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='new/'),
        ),
    ]
